devices = [ 
{'CE-A1':{
    'device_type':'juniper',
    'ip':'127.0.0.1',
    'port':'22221',
    'username':'root',
    'password':'Vagrant',
    'verbose':True,
}},
{'CE-B1':{
    'device_type':'juniper',
    'ip':'127.0.0.1',
    'port':'22222',
    'username':'root',
    'password':'Vagrant',
    'verbose':True,
}},
{'PE1':{
    'device_type':'juniper',
    'ip':'127.0.0.1',
    'port':'22223',
    'username':'root',
    'password':'Vagrant',
    'verbose':True,
}},
{'P1':{
    'device_type':'juniper',
    'ip':'127.0.0.1',
    'port':'22224',
    'username':'root',
    'password':'Vagrant',
    'verbose':True,
}},

{'P2':{
    'device_type':'juniper',
    'ip':'127.0.0.1',
    'port':'22225',
    'username':'root',
    'password':'Vagrant',
    'verbose':True,
}},

{'PE2':{
    'device_type':'juniper',
    'ip':'127.0.0.1',
    'port':'22226',
    'username':'root',
    'password':'Vagrant',
    'verbose':True,
}},

{'CE-A2':{
    'device_type':'juniper',
    'ip':'127.0.0.1',
    'port':'22227',
    'username':'root',
    'password':'Vagrant',
    'verbose':True,
}},


{'CE-B2':{
    'device_type':'juniper',
    'ip':'127.0.0.1',
    'port':'22228',
    'username':'root',
    'password':'Vagrant',
    'verbose':True,
}},
]
